### PR TITLE
Feature/distributions part2

### PR DESCRIPTION
**Pull request by whaeck**
This PR adds the following one dimensional function components:
- Legendre and tabulated angular distributions
- tabulated energy distributions

This PR adds the following two dimensional function components:
- Legendre angular distribution data on a grid
- Tabulated angular distribution data on a grid
- Tabulated energy distribution data on a grid

This is based on the latest scion developments

### CODE REVIEW

**Review by cjosey — COMMENTED** [review]
[Questions]
Are there no equivalent Python tests for the energy-angle evaluation?
Do operators like `chunk(energy, angle)` work with `numpy.ndarray` inputs or do you have to construct an `numpy.vectorize` object?

Otherwise, looks good.

Edit: I see now, the Python interface is in part 3.

**Review by cjosey — APPROVED** [review]

**Comment by whaeck** [comment]
chunk(energy, angle) is a function call that interpolates on the the data.

**Comment by cjosey** [comment]
> chunk(energy, angle) is a function call that interpolates on the the data.

I meant more in this sense:
```python
import numpy as np

e_vals = np.logspace(-5, 8, 100)
mu_vals = np.linspace(-1, 1, 50)

e_mesh, mu_mesh = np.meshgrid(e_vals, mu_vals)

val = chunk(e_mesh, mu_mesh)
```

If it's only a scalar argument, I could just do
```python
chunk_vecfun = np.vectorize(chunk)

val = chunk_vecfun(e_mesh, mu_mesh)
```

**Comment by whaeck** [comment]
Oh, that's an interesting use case. 

The function is specifically only for scalar arguments, and only returns a double. I won't be able to do it with the call operator - as C++ requires the same return type when using operator overloading. Still, I'll look into it.

**Pull request merged**
